### PR TITLE
add unix shell style patterns to ignore file list

### PR DESCRIPTION
**Pull request by vasilishin**
Hi @Falldog. I'm added unix shell style patterns to ignore file list because i can't exclude all folder like `*migrations/*` or some files by pattern `[seq]`.

### CODE REVIEW

**Comment by Falldog** [comment]
@vasilishin sorry for late reply your pull request
Thanks for your contribution, it's a good feature for `pyconcrete`
I will review it later

First question is, what is the new file need to be committed?
`test/data/test1.py`
`test/data/test2.py`

**Comment by vasilishin** [comment]
@Falldog this files need for test cases, but we can prepare this files in test setup.

**Comment by Falldog** [comment]
@vasilishin 
few questions
* I had commented a question on code about pattern with `*`
* Please help to create new test class, like `TestAdminIgnoreFilesScript`
* Please remove commit file `test/data/test[1,2].py`, prepare it in test case
Thanks

**Comment by vasilishin** [comment]
@Falldog, i did changes in test admin file

**Comment by vasilishin** [comment]
Thanks @Falldog, I'm fixed case with `test.py, a_test.py, b_test.py` file names. But we should use full path names because some files in other directories may have same names
```
project/users/models.py
project/blog/models.py
```
For excluding only `project/blog/models.py` file you can use `bolg/models.py` pattern.

**Pull request merged**
