### PR TITLE
New import hook used - now works with Django

### PR DESCRIPTION
**Pull request by samirotiv**
I have not bothered to implement encryption of packages. This is also very easy to do. Just giving you a pull request to make it more robust.

### CODE REVIEW

**Comment by Falldog** [comment]
It's cool! 
Thanks for your contribution, but I just run the test pye_test_performance.py is failed. Could you help to check it out? Thanks

**Comment by Falldog** [comment]
BTW, you can just execute below command to run test 
```shell
cd %pyconcrete%/test
python pye_test_performance.py
```
It will get current pyconcrete code to test

**Comment by samirotiv** [comment]
Sure, I will as soon as I have a little spare time. :)

Pyconcrete has been an enormous help at an urgent time. Thanks a lot! It was just this little thing that caused it to fail with Django, though. 

I wanted to have a private discussion about Pyconcrete with you. Let me see if I can figure out a way to contact you.

**Comment by Falldog** [comment]
Hi @samirotiv,

I just spend some time to integrate with your code,  fix some issue and add a new testing case.
It's a great solution for pyconcrete, thanks very much.

And I am sorry that I can't merge it before the testing issue be fixed.
I will close the pull request directly since I was integrated your code in latest commit.

**Pull request closed without merging**
